server:
  port: ${HTTP_SERVER_PORT:8090}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

instance:
  key: ${INSTANCE_KEY:user-service}
  id: ${INSTANCE_ID:1}

spring:
  main:
    banner-mode: off
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:user_service}
    username: ${POSTGRES_USER_NAME:postgres}
    password: ${POSTGRES_PASSWORD:test}
  jpa:
    show-sql: 'true'
    open-in-view: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: 'true'
        format_sql: 'true'





